-- MySQL Script generated by MySQL Workbench
-- Mon Aug 17 13:21:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema face
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema face
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `face` DEFAULT CHARACTER SET utf8 ;
USE `face` ;

-- -----------------------------------------------------
-- Table `face`.`mst_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `face`.`mst_user` ;

CREATE TABLE IF NOT EXISTS `face`.`mst_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
  `username` VARCHAR(16) NOT NULL COMMENT 'ユーザ名',
  `password` VARCHAR(255) NOT NULL COMMENT 'パスワード',
  `photo` VARCHAR(255) NOT NULL COMMENT '写真',
  `s3_key` VARCHAR(255) NOT NULL COMMENT 'S3のキー名',
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '管理者フラグ',
  `last_login_at` TIMESTAMP NULL DEFAULT NULL COMMENT '最終ログイン日時',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '更新日',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = 'ユーザマスタ';


-- -----------------------------------------------------
-- Table `face`.`qr_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `face`.`qr_token` ;

CREATE TABLE IF NOT EXISTS `face`.`qr_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `mst_user_id` BIGINT NOT NULL COMMENT 'ユーザマスタの外部キー',
  `qr_token` VARCHAR(255) NOT NULL COMMENT 'QRトークン',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '更新日',
  PRIMARY KEY (`id`),
  INDEX `fk_mst_user_id_of_qr_token_idx` (`mst_user_id` ASC),
  CONSTRAINT `fk_mst_user_id_of_qr_token`
    FOREIGN KEY (`mst_user_id`)
    REFERENCES `face`.`mst_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'QRトークン';


-- -----------------------------------------------------
-- Table `face`.`face_recognition_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `face`.`face_recognition_result` ;

CREATE TABLE IF NOT EXISTS `face`.`face_recognition_result` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `mst_user_id` BIGINT NOT NULL COMMENT 'ユーザマスタの外部キー',
  `source_image` VARCHAR(255) NOT NULL COMMENT '比較基の画像',
  `source_image_s3_key` VARCHAR(255) NOT NULL COMMENT '比較基画像のs3のキー名',
  `target_image` VARCHAR(255) NOT NULL COMMENT '比較先の画像',
  `target_image_s3_key` VARCHAR(255) NOT NULL COMMENT '比較先画像のs3のキー名',
  `result` DECIMAL(13,10) NOT NULL COMMENT '顔認証結果',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '更新日',
  PRIMARY KEY (`id`),
  INDEX `fk_mst_user_id_of_face_recognition_result_idx` (`mst_user_id` ASC),
  CONSTRAINT `fk_mst_user_id_of_face_recognition_result`
    FOREIGN KEY (`mst_user_id`)
    REFERENCES `face`.`mst_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '顔認証結果';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
